#!/bin/bash

if [ ! -n "$2" ]
then
    echo "Usage: `basename $0` secret key [context]"
    exit 1
fi

if [ ! -n "$3" ]
then
    SECRET64=`kubectl get secret $1 -o go-template="{{index .data \"$2\"}}"`
else
    SECRET64=`kubectl --context $3 get secret $1 -o go-template="{{index .data \"$2\"}}"`
fi

echo $SECRET64 | base64 -D | pbcopy
